# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='repeated_packed.proto',
  package='',
  serialized_pb='\n\x15repeated_packed.proto\"\x1a\n\x05Thing\x12\x11\n\x05parts\x18\x04 \x03(\x05\x42\x02\x10\x01')




_THING = descriptor.Descriptor(
  name='Thing',
  full_name='Thing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='parts', full_name='Thing.parts', index=0,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['Thing'] = _THING

class Thing(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _THING
  
  # @@protoc_insertion_point(class_scope:Thing)

# @@protoc_insertion_point(module_scope)
